# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys #send arguments to the application from command line.
from PyQt5 import QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget
from PyQt5.QtGui import QIcon

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_number1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_number1.setGeometry(QtCore.QRect(70, 50, 91, 51))
        self.lbl_number1.setObjectName("lbl_number1")
        self.lbl_number2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_number2.setGeometry(QtCore.QRect(70, 120, 61, 41))
        self.lbl_number2.setObjectName("lbl_number2")
        self.text_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.text_1.setGeometry(QtCore.QRect(150, 70, 113, 20))
        self.text_1.setObjectName("text_1")
        self.text_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.text_2.setGeometry(QtCore.QRect(150, 130, 113, 20))
        self.text_2.setObjectName("text_2")
        self.addition = QtWidgets.QPushButton(self.centralwidget)
        self.addition.setGeometry(QtCore.QRect(160, 230, 75, 23))
        self.addition.setObjectName("addition")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(300, 70, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(300, 130, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(90, 430, 47, 13))
        self.lbl_result.setObjectName("lbl_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_number1.setText(_translate("MainWindow", "Number 1"))
        self.lbl_number2.setText(_translate("MainWindow", "Number 2"))
        self.addition.setText(_translate("MainWindow", "Addition"))
        self.lbl_result.setText(_translate("MainWindow", "Result"))

class my_app (QtWidgets.QMainWindow):
    def __init__(self):
        super(my_app, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.addition.clicked.connect(self.calculate)

    def calculate(self):
        sender = self.sender()
        print(sender.text())
        result = 0
        if sender.text() == 'Addition':
            result = int(self.ui.text_1.text()) + int(self.ui.text_2.text())
        self.ui.lbl_result.setText(str(result))
def app():
    app = QtWidgets.QApplication(sys.argv)
    win = my_app()
    win.show()
    sys.exit(app.exec_())

app()